import type { Metadata } from "next";

import "../styles/globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Blog Rozane Fregulia",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      
      <body className="min-h-screen w-full flex flex-col"><Header />{children}<Footer /></body>
      
    </html>
  );
}
